apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: propDevelopment-view
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "namespaces", "nodes", "replicationcontrollers", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
