apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: boris-propDevelopment-admin-binding
subjects:
- kind: User
  name: vadim
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: propDevelopment-admin
  apiGroup: rbac.authorization.k8s.io
