@startmindmap risks
*[#lightgreen] Безопасность системы
**[#lightyellow] Публичные данные
*** Рекламные материалы
****[#yellow]: **искажение данных**
Может повлечь незначительные потери;
*** Характеристики объектов на витрине
*** Оферты
*** Инструкции по использованию приложений
*** Тарифы на обслуживание ЖКХ
**[#lightyellow] Внутренние данные
*** База данных объектов недвижимости
*** Внутренние регламенты и методологии
*** Отчеты и аналитика (исключая финансовую)
**[#lightyellow]:Конфиденциальные 
данные;
*** Потоки финансовых платежей
*** Персональные данные клиентов
*** Переписка с клиентами
*** Исходный код программ
**[#lightyellow] Секретные данные
*** Данные об интеграции с госсистемами
*** Ключи доступа к ИС
@endmindmap
