@startmindmap risks
*[#lightgreen] Безопасность системы
**[#lightyellow] Публичные данные
***:- Рекламные материалы
- Характеристики объектов на витрине
- Оферты
- Инструкции по использованию приложений
- Тарифы на обслуживание ЖКХ;
****[#yellow]: **искажение данных**
От незначительных до умеренных репутационных потерь;
****[#yellow]: **потеря данных**
Репутационные потери;


**[#lightyellow] Внутренние данные
***:- База данных объектов недвижимости
- Внутренние регламенты и методологии
- Отчеты и аналитика (исключая финансовую);
****[#orange]: **утечка данных**
- Репутационные потери
- потеря конкурентного преимущества;
****[#orange]: **потеря данных**
- нарушение нормального функционирования компании;
****[#orange]: **искажение данных**
- нарушение нормального функционирования компании;
****[#orange]: **некачественные данные**
- потеря производительности
- нарушение функционирования;


**[#lightyellow]:Конфиденциальные 
данные;
***:- Потоки финансовых платежей
- Персональные данные клиентов
- Переписка с клиентами
- Исходный код программ;
****[#orange]: **утечка данных**
- Репутационные потери
- потеря конкурентного преимущества;
****[#orange]: **потеря данных**
- нарушение нормального функционирования компании;
****[#orange]: **искажение данных**
- нарушение нормального функционирования компании;
****[#orange]: **некачественные данные**
- потеря производительности
- нарушение функционирования;
**[#lightyellow] Секретные данные
***:- Данные об интеграции с госсистемами
- Ключи доступа к ИС;
****[#red]: **искажение данных**
Нарушение функционирования критически важных систем;
****[#red]: **потеря данных**
Нарушение функционирования критически важных систем;
****[#red]: **утечка данных**
Штрафы, репутационные потери, отстранение от работы;
@endmindmap
