---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: admin-front-end
  name: admin-front-end-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: admin-front-end
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: admin-front-end
  name: admin-front-end-app
spec:
  containers:
  - image: nginx
    name: admin-front-end-app
    ports:
    - containerPort: 80
